-- ALTER TABLE "Message_v2" ADD COLUMN "model_id" text;--> statement-breakpoint
-- ALTER TABLE "User" ADD COLUMN "provider" varchar;--> statement-breakpoint
-- ALTER TABLE "User" ADD COLUMN "type" varchar;
